# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose automation suite: RegressionSuite, SmokeSuite, SanitySuite'
        required: true
        default: RegressionSuite

      browser:
        description: 'Choose browser suite: chrome, edge, firefox'
        required: true
        default: chrome


jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Install Edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run automation suite
        run: mvn clean install -DciCd=true  -Dbrowser=${{github.event.inputs.browser}} -DsuiteXmlFile=suites/${{github.event.inputs.suite}} -PCustomSuite

      - name: Publish suite results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: SuiteResults
          path: |
            target/extentReports
            target/logs/RegressionLogs.log